#!/bin/sh
# Nagios JMX plugin.
#

#JAVA_CMD=`which java`
JAVA_CMD=/usr/bin/java
echo $JAVA_CMD >> /tmp/hi.log

if [ -z $JAVA_CMD ]
then
  if [ -x $JAVA_HOME/bin/java ]
  then
    JAVA_CMD=$JAVA_HOME/bin/java
  else
    echo JMX CRITICAL - java not found. >> /tmp/hi.log
    exit 2
  fi
fi

DIR=`dirname $0`
#$JAVA_CMD 2>&1 >> /tmp/hi.log
$JAVA_CMD -jar $DIR/check_jmx.jar "$@"
