#!/bin/sh
set -e -x
#start up  - to be run before all modules
java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=$2/<%= bahmni_core %>.omod:$1/<%= openmrs_war_file_name %>.war --changeLogFile=migrations/dependent-modules/liquibase.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update

java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=$2/<%= openmrs_atomfeed %>.omod:$1/<%= openmrs_war_file_name %>.war --changeLogFile=liquibase.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update
java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=$2/<%= openmrs_appframework %>.omod:$1/<%= openmrs_war_file_name %>.war --changeLogFile=liquibase.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update
java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=$2/<%= openmrs_calculation %>.omod:$1/<%= openmrs_war_file_name %>.war --changeLogFile=liquibase.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update
java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=$2/<%= openmrs_metadatamapping %>.omod:$1/<%= openmrs_war_file_name %>.war --changeLogFile=liquibase.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update
java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=$2/<%= openmrs_providermanagement %>.omod:$1/<%= openmrs_war_file_name %>.war --changeLogFile=liquibase.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update
java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=$2/<%= openmrs_uiframework %>.omod:$1/<%= openmrs_war_file_name %>.war --changeLogFile=liquibase.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update
java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=$2/<%= bahmni_elisatomfeedclient %>.omod:$1/<%= openmrs_war_file_name %>.war --changeLogFile=liquibase.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update
java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=$2/<%= bahmni_openerpatomfeedclient %>.omod:$1/<%= openmrs_war_file_name %>.war --changeLogFile=liquibase.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update


java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=$2/<%= bahmni_core %>.omod:$1/<%= openmrs_war_file_name %>.war --changeLogFile=liquibase.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update

java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=$3/<%= bahmni_apps %>.omod:$1/<%= openmrs_war_file_name %>.war --changeLogFile=liquibase.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update

java -Dliquibase.databaseChangeLogTableName=liquibasechangelog -Dliquibase.databaseChangeLogLockTableName=liquibasechangeloglock -jar openmrs/WEB-INF/lib/liquibase-core-2.0.5.jar --driver=com.mysql.jdbc.Driver --classpath=<%= temp_dir%>/<%= bahmni_elisatomfeedclient %>/lib/<%= atomfeed_client %>.jar:$1/<%= openmrs_war_file_name %>.war --changeLogFile=sql/db_migrations.xml --url=jdbc:mysql://localhost:3306/openmrs --username=root --password=password update  -DschemaName=openmrs 