#!/bin/sh
#
# /etc/init.d/wvdiald
#
# chkconfig: 345 97 05
# description: wvdial start
#
# processname: wvdial
# config: /etc/wvdial.conf

# Source function library.
. /etc/rc.d/init.d/functions


RETVAL=0
prog="wvdial"
start() {
    echo -e "Starting Wvdial ..."
    USBmodem=`cat /etc/wvdial.conf | grep '^Modem =' | cut -f2 -d'=' | cut -f2 -d' '`
    counter=10
    while([ ! -e "$USBmodem" ] && [ "$counter" -gt 0 ])
        do
            sleep 2
            counter=$((counter-1))
        done
    daemon --user root --check wvdial "wvdial &"
    RETVAL=$?
    [ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
    echo
}

stop() {
    echo -e "Stopping Wvdial ..."
    pkill -9 -f wvdial
    pkill -9 -f pppd
    RETVAL=$?
    [ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
    echo
}

status() {
    ps aux | grep ppp | grep -v grep
    if([ $? -eq 0 ]) then
        echo -e "$prog is Running.."
    else
        echo -e "$prog is Stopped."
    fi
    echo
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    condrestart)
        if [ -f /var/lock/subsys/$prog ] ; then
            stop
            # avoid race
            sleep 3
            start
        fi
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|condrestart|status}"
        RETVAL=1
esac
exit $RETVAL