$temp_dir = "/bahmni_temp"
$logs_dir = "${temp_dir}/logs"
$package_dir = "/packages"
$java_home = "/usr/java/default"
$java = "/usr/bin/java"
$os_path = "/sbin:/bin:/usr/sbin/:/usr/bin:/usr/local/bin:/usr/local/sbin"