$temp_dir = "/bahmni_temp"
$logs_dir = "${temp_dir}/logs"
$package_dir = "/packages"
$java_home = "/usr/java/default"
$os_path = "/sbin:/bin:/usr/sbin/:/usr/bin:/usr/local/bin:/usr/local/sbin"
$local_repo_path = "${package_dir}/localrepo"
$local_repo_name = "local"